import { extendTailwindMerge } from "tailwind-merge";

// Register only the reviewed semantic names. Without these, merging mistakes
// text sizes for colors and cannot replace primitive corners or compound insets.
const merge = extendTailwindMerge({
  extend: {
    theme: {
      text: [
        "landing-hero", "display", "page-title", "section-title",
        "card-title", "body-lg", "body", "body-sm",
        "label", "caption", "overline", "metric",
        "landing-button", "landing-eyebrow", "landing-brand", "landing-navigation",
        "landing-hero-fluid", "landing-hero-description", "landing-hero-footer", "landing-hero-art-label",
        "landing-hero-art-metric", "landing-scene-watermark", "landing-scene-number", "landing-scene-heading",
        "landing-scene-description", "landing-scene-benefit", "landing-scene-benefit-marker", "landing-demo-disclaimer",
        "landing-demo-status", "landing-inspector-heading", "landing-control-metric", "landing-control-hint",
        "landing-chart-heading", "landing-demo-micro", "landing-report-micro", "landing-report-meta",
        "landing-report-heading", "landing-section-heading", "landing-section-description", "landing-feature-card-number",
        "landing-feature-card-heading", "landing-feature-card-body", "landing-feature-card-outcome", "landing-feature-detail-heading",
        "landing-feature-detail-description", "landing-feature-detail-step", "landing-feature-detail-step-number", "landing-feature-detail-outcome",
        "landing-plan-name", "landing-plan-badge", "landing-plan-summary", "landing-price",
        "landing-plan-feature", "landing-pricing-note", "landing-closing-heading", "landing-closing-description",
        "landing-footer-company", "landing-footer-legal", "landing-feature-detail-heading-stacked", "landing-navigation-stacked",
        "landing-hero-fluid-stacked", "landing-scene-heading-stacked", "landing-section-heading-narrow", "landing-feature-card-heading-narrow",
        "landing-feature-detail-heading-narrow", "landing-brand-narrow", "landing-navigation-narrow", "landing-hero-fluid-narrow",
        "landing-scene-heading-narrow", "landing-closing-heading-narrow", "landing-concept-hero-fluid", "landing-concept-inquiry-eyebrow",
        "landing-concept-inquiry-title", "landing-concept-inquiry-description", "landing-concept-inquiry-dismiss", "landing-concept-inquiry-label",
        "landing-concept-inquiry-optional", "landing-concept-inquiry-error", "landing-concept-inquiry-privacy", "landing-concept-inquiry-feedback",
        "landing-action", "landing-footer-heading", "landing-feature-detail-copy-narrow", "landing-demo-meta",
        "landing-feature-card-copy-narrow", "landing-concept-footer-body", "landing-preview-control-value-expanded", "landing-report-heading-narrow",
        "landing-chart-heading-narrow", "landing-demo-title", "landing-compact-action", "landing-feature-supporting-note",
        "landing-plan-feature-marker", "landing-scene-benefit-narrow", "landing-control-heading", "landing-feature-card-link",
        "landing-inquiry-plan", "landing-footer-body", "landing-price-unit", "landing-narrative-copy-narrow",
        "landing-demo-caption", "landing-demo-control-label", "landing-replay-icon",
      ],
      radius: [
        "control", "panel", "popover", "fixture-marker",
        "pill", "landing-skip-link", "landing-button", "landing-demo-surface",
        "landing-brand-mark", "landing-ellipse", "landing-glass-panel", "landing-hero-chart-bar",
        "landing-demo-backplate", "landing-demo-card", "landing-floorplan", "landing-floorplan-entry",
        "landing-control-pendant", "landing-report-progress", "landing-map-tool", "landing-map-hint",
        "landing-preview-label-bar", "landing-preview-detail", "landing-preview-chart-bar", "landing-preview-stage",
        "landing-preview-window-expanded", "landing-preview-stage-narrow", "landing-preview-window-expanded-narrow", "landing-inquiry-modal",
        "landing-concept-inquiry-privacy", "landing-concept-inquiry-modal-stacked", "landing-compact-control", "landing-compact-summary-surface",
        "landing-inset-surface", "landing-compact-choice-control",
      ],
      spacing: [
        "shell-rail", "landing-anchor-anchor-offset", "landing-skip-link-top", "landing-button-inset",
        "landing-brand-mark-inset", "landing-navigation-gap", "landing-hero-orbit-near-right", "landing-hero-orbit-far-right",
        "landing-hero-frame-gap", "landing-hero-frame-block-inset", "landing-hero-heading-margin", "landing-hero-actions-gap",
        "landing-hero-actions-top-space", "landing-hero-footer-bottom", "landing-hero-art-background-card-inset", "landing-hero-art-metric-card-inset",
        "landing-hero-art-chart-gap", "landing-hero-art-chart-top-space", "landing-scene-frame-gap", "landing-scene-frame-block-inset",
        "landing-scene-number-margin", "landing-scene-heading-margin", "landing-scene-benefit-margin", "landing-scene-benefit-top-inset",
        "landing-demo-backplate-right", "landing-demo-backplate-bottom", "landing-demo-frame-inline-inset", "landing-demo-disclaimer-inset",
        "landing-floorplan-caption-inset", "landing-parking-spaces-gap", "landing-demo-map-label-inset", "landing-demo-status-label-gap",
        "landing-demo-status-label-inset", "landing-inspector-property-top-inset", "landing-control-pendant-cord-top", "landing-control-caption-bottom",
        "landing-control-panel-inset", "landing-control-slider-margin", "landing-control-hint-margin", "landing-demo-result-top-space",
        "landing-chart-content-inset", "landing-chart-heading-gap", "landing-chart-frame-top-space", "landing-chart-frame-inset",
        "landing-chart-axis-top", "landing-chart-axis-bottom", "landing-chart-footer-top-space", "landing-chart-legend-gap",
        "landing-report-content-inset", "landing-report-controls-bottom-space", "landing-report-format-inset", "landing-report-sheet-inset",
        "landing-report-heading-margin", "landing-report-divider-margin", "landing-report-footer-top-inset", "landing-report-history-inset",
        "landing-map-content-inset", "landing-map-toolbar-gap", "landing-map-hint-left", "landing-map-result-top-space",
        "landing-section-frame-block-inset", "landing-feature-card-inset", "landing-feature-card-heading-margin", "landing-feature-card-link-top-space",
        "landing-preview-canvas-position-inset", "landing-preview-control-inset", "landing-preview-slider-top-space", "landing-preview-value-top-space",
        "landing-preview-schedule-gap", "landing-preview-schedule-top-space", "landing-preview-chart-gap", "landing-preview-chart-margin",
        "landing-preview-chart-inset", "landing-preview-report-inset", "landing-feature-detail-block-inset", "landing-feature-frame-gap",
        "landing-feature-detail-heading-margin", "landing-feature-steps-margin", "landing-feature-detail-outcome-inset", "landing-feature-detail-link-gap",
        "landing-feature-detail-link-top-space", "landing-preview-stage-inset", "landing-preview-toolbar-expanded-inline-inset", "landing-preview-canvas-expanded-position-inset",
        "landing-preview-control-expanded-inset", "landing-preview-slider-expanded-top-space", "landing-preview-schedule-expanded-top-space", "landing-preview-chart-expanded-margin",
        "landing-preview-chart-expanded-gap", "landing-pricing-intro-bottom-space", "landing-pricing-card-inset", "landing-pricing-value-row-gap",
        "landing-pricing-value-row-bottom-inset", "landing-pricing-features-margin", "landing-pricing-note-margin", "landing-inquiry-plan-inset",
        "landing-closing-block-inset", "landing-closing-heading-margin", "landing-closing-description-margin", "landing-footer-body-block-inset",
        "landing-footer-main-gap", "landing-footer-main-bottom-inset", "landing-footer-description-margin", "landing-footer-heading-margin",
        "landing-footer-contacts-gap", "landing-footer-legal-top-inset", "landing-feature-frame-medium-gap", "landing-scene-frame-medium-gap",
        "landing-feature-detail-stacked-block-inset", "landing-preview-stage-stacked-inset", "landing-header-frame-stacked-gap", "landing-navigation-login-stacked-inline-inset",
        "landing-hero-frame-stacked-gap", "landing-hero-frame-stacked-block-inset", "landing-hero-illustration-stacked-top-space", "landing-hero-art-background-card-stacked-inset",
        "landing-scene-frame-stacked-block-inset", "landing-demo-backplate-stacked-bottom", "landing-inspector-stacked-gap", "landing-control-panel-stacked-margin",
        "landing-footer-main-stacked-gap", "landing-anchor-narrow-anchor-offset", "landing-section-frame-block-inset-narrow", "landing-feature-card-narrow-inset",
        "landing-feature-card-link-narrow-top-space", "landing-preview-canvas-expanded-narrow-position-inset", "landing-preview-control-expanded-narrow-inset", "landing-preview-slider-expanded-narrow-top-space",
        "landing-preview-schedule-expanded-narrow-top-space", "landing-preview-chart-expanded-narrow-margin", "landing-navigation-login-narrow-inline-inset", "landing-hero-actions-narrow-gap",
        "landing-hero-illustration-narrow-top-space", "landing-scene-frame-narrow-gap", "landing-scene-frame-narrow-block-inset", "landing-scene-number-narrow-bottom-space",
        "landing-scene-benefit-narrow-top-space", "landing-scene-benefit-narrow-top-inset", "landing-demo-frame-compact-inline-inset", "landing-demo-title-narrow-gap",
        "landing-demo-content-compact-inset", "landing-report-heading-narrow-top-space", "landing-html-scroll-padding", "landing-concept-footer-body-inset",
        "landing-concept-inquiry-header-inset", "landing-concept-inquiry-description-margin", "landing-concept-inquiry-form-gap", "landing-concept-inquiry-form-inset",
        "landing-concept-inquiry-fields-gap", "landing-concept-inquiry-field-gap", "landing-concept-inquiry-message-inset", "landing-concept-inquiry-message-description-space",
        "landing-concept-inquiry-consent-gap", "landing-concept-inquiry-feedback-action-top-space", "landing-html-stacked-scroll-padding", "landing-concept-inquiry-header-stacked-inset",
      ],
    }
  }
});

export function cn(...classes: Array<string | false | null | undefined>) {
  return merge(classes.filter(Boolean).join(" "));
}
