listener 8883
allow_anonymous false
cafile /mosquitto/certs/mqtt-ca.crt
certfile /mosquitto/certs/mqtt-server.crt
keyfile /mosquitto/certs/mqtt-server.key
crlfile /mosquitto/certs/mqtt-client.crl
require_certificate true
use_identity_as_username true
tls_version tlsv1.2
acl_file /mosquitto/config/mosquitto.acl
persistence false
log_dest stdout
